export const MetricTypes = {
  percentage: "%",
  gigabyte: "GB",
  megabyte: "MB",
  peers: "connected",
  ethereum: "ETH",
  taiko: "TKO",
  hours: "hours",
  minutes: "minutes",
  blockheight: "blocks",
  proposer: "blocks",
  prover: "blocks",
  total: "",
  gas: "gwei",
};
